# Output-Full Analysis

The function of this notebook serves to run some analysis on the results that we have find after retriving from the website.

In [1]:
# Display all the inputs

import pandas as pd

In [2]:
df = pd.read_csv("./output-full/posts.csv")
df.head()

,thread_id,thread_title,thread_url,post_id,is_opening_post,floor,author,posted_at,content,image_urls,link_urls,thread_page,source_url
0,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778403,True,楼主,hwy1368,2018-8-19 11:10:40,【2012年】\n国内的肝癌患者主要是由乙肝病毒和血吸虫引起的，近年来脂肪肝引起的肝癌慢慢增...,"[""http://www.yuaigongwu.com/template/comiis_xi...","[""http://www.yuaigongwu.com/member.php?mod=log...",1,http://www.yuaigongwu.com/thread-59646-1-1.html
1,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778497,False,沙发,chjw,2018-8-19 16:25:43,楼主用的靶向药都是正版吗？\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html
2,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778498,False,板凳,chjw,2018-8-19 16:26:10,还在坚持游泳吗？\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html
3,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778510,False,地板,best500728060,2018-8-19 17:23:08,E7080，剂量12mg/天。AFP迅速下降。幅度60%每周。效果很好呢。\n希望瑞戈非尼也...,[],[],1,http://www.yuaigongwu.com/thread-59646-1-1.html
4,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778591,False,5 #,hwy1368,2018-8-19 21:53:20,谢谢您的祝福，瑞格菲尼有无效果还没看结果呢。\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8604 entries, 0 to 8603
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   thread_id        8604 non-null   int64
 1   thread_title     8604 non-null   str
 2   thread_url       8604 non-null   str
 3   post_id          8604 non-null   int64
 4   is_opening_post  8604 non-null   bool
 5   floor            8604 non-null   str
 6   author           8604 non-null   str
 7   posted_at        8604 non-null   str
 8   content          8604 non-null   str
 9   image_urls       8604 non-null   str
 10  link_urls        8604 non-null   str
 11  thread_page      8604 non-null   int64
 12  source_url       8604 non-null   str
dtypes: bool(1), int64(3), str(9)
memory usage: 815.2 KB

In [4]:
df.drop_duplicates()

,thread_id,thread_title,thread_url,post_id,is_opening_post,floor,author,posted_at,content,image_urls,link_urls,thread_page,source_url
0,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778403,True,楼主,hwy1368,2018-8-19 11:10:40,【2012年】\n国内的肝癌患者主要是由乙肝病毒和血吸虫引起的，近年来脂肪肝引起的肝癌慢慢增...,"[""http://www.yuaigongwu.com/template/comiis_xi...","[""http://www.yuaigongwu.com/member.php?mod=log...",1,http://www.yuaigongwu.com/thread-59646-1-1.html
1,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778497,False,沙发,chjw,2018-8-19 16:25:43,楼主用的靶向药都是正版吗？\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html
2,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778498,False,板凳,chjw,2018-8-19 16:26:10,还在坚持游泳吗？\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html
3,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778510,False,地板,best500728060,2018-8-19 17:23:08,E7080，剂量12mg/天。AFP迅速下降。幅度60%每周。效果很好呢。\n希望瑞戈非尼也...,[],[],1,http://www.yuaigongwu.com/thread-59646-1-1.html
4,59646,早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。,http://www.yuaigongwu.com/thread-59646-1-1.html,778591,False,5 #,hwy1368,2018-8-19 21:53:20,谢谢您的祝福，瑞格菲尼有无效果还没看结果呢。\n来自安卓APP客户端,[],"[""http://majia.yuaigongwu.com""]",1,http://www.yuaigongwu.com/thread-59646-1-1.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8599,37683,原发肝癌，7080使用请教,http://www.yuaigongwu.com/thread-37683-1-1.html,916647,False,211 #,小媛,2019-8-25 12:24:58,楼主还在么，私一个7080和其他药的渠道\n来自苹果APP客户端,[],"[""http://majia.yuaigongwu.com""]",22,http://www.yuaigongwu.com/forum.php?mod=viewth...
8600,37683,原发肝癌，7080使用请教,http://www.yuaigongwu.com/thread-37683-1-1.html,918619,False,212 #,特别关注,2019-9-1 22:06:04,萨德 发表于 2018-08-20 14:26\n我家一直用的8mg，现在还有效，不需要加计...,[],"[""http://www.yuaigongwu.com/forum.php?mod=redi...",22,http://www.yuaigongwu.com/forum.php?mod=viewth...
8601,37683,原发肝癌，7080使用请教,http://www.yuaigongwu.com/thread-37683-1-1.html,928588,False,213 #,肝胆肝胆相照,2019-10-8 20:47:39,巧克努力 发表于 2017-05-17 22:13\n还没找到呀，私信给你\n同求！多谢。\...,[],"[""http://www.yuaigongwu.com/forum.php?mod=redi...",22,http://www.yuaigongwu.com/forum.php?mod=viewth...
8602,37683,原发肝癌，7080使用请教,http://www.yuaigongwu.com/thread-37683-1-1.html,936062,False,214 #,大美山河js,2019-11-4 13:24:59,巧克努力 发表于 2018-10-16 10:36\n我是先加量然后联药在用\n求7080渠...,[],"[""http://www.yuaigongwu.com/forum.php?mod=redi...",22,http://www.yuaigongwu.com/forum.php?mod=viewth...
8603,37683,原发肝癌，7080使用请教,http://www.yuaigongwu.com/thread-37683-1-1.html,936063,False,215 #,大美山河js,2019-11-4 13:26:52,平安就是福。 发表于 2017-4-26 09:11\n私信给你吧\n求7080渠道，谢谢。...,[],"[""http://www.yuaigongwu.com/forum.php?mod=redi...",22,http://www.yuaigongwu.com/forum.php?mod=viewth...